fix(Search.component.tsx) : src/components/Search.component.tsx(61,23): error TS2551: Property 'tag' does not exist on type 'ProductTypes'. Did you mean 'tags'? src/components/Search.component.tsx(61,32): error TS7006: Parameter 't' implicitly has an 'any' type.