fix(SingleProduct.page.tsx) : src/pages/SingleProduct.page.tsx(26,70): error TS2345: Argument of type '{ _id: string; brand: string; category: 'protein'; subCategory: string; dietaryType: 'veg'; images: string[]; name: string; numReviews: number; price: number; rating: number; avgRating: number; tags: never[]; ... 7 more ...; warnings: never[]; }' is not assignable to parameter of type 'ProductTypes | (() => ProductTypes)'.   Type '{ _id: string; brand: string; category: 'protein'; subCategory: string; dietaryType: 'veg'; images: string[]; name: string; numReviews: number; price: number; rating: number; avgRating: number; tags: never[]; ... 7 more ...; warnings: never[]; }' is missing the following properties from type 'ProductTypes': soldCount, variant