fix(RumbleText.component.tsx) : src/components/RumbleText.component.tsx(1,36): error TS6133: 'Dispatch' is declared but its value is never read. src/components/RumbleText.component.tsx(1,51): error TS6133: 'SetStateAction' is declared but its value is never read.